---
# tasks file for python
    - name: Install Python and pip
      package:
        name: python3-pip
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install virtualenv package
      pip:
        name: virtualenv
        state: latest
      when: ansible_os_family == 'Debian'